const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const LS={get(k,d){try{const v=localStorage.getItem(k);return v==null?d:JSON.parse(v)}catch{return d}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}},del(k){try{localStorage.removeItem(k)}catch{}}};
const CROPS=['Tomato','Rice','Wheat','Potato','Maize','Cotton','Chili'],EM={Tomato:'🍅',Rice:'🌾',Wheat:'🌿',Potato:'🥔',Maize:'🌽',Cotton:'☁️',Chili:'🌶️'};
const dz=(c,n,s,d,sy,ca,tr,pv)=>({c,n,s,d,sy:sy.split('|'),ca:ca.split('|'),tr:tr.split('|'),pv:pv.split('|')});
const FP='Use resistant varieties|Rotate crops every season|Keep leaves dry and field clean|Scout plants weekly';
const D=[
dz('Tomato','Early Blight','Moderate','A fungal disease (Alternaria solani) that starts on older leaves and spreads upward in warm, humid weather.','Brown spots on leaves|Concentric ring patterns|Yellowing around infected areas|Premature leaf drop','Fungal infection|High humidity|Poor air circulation|Wet foliage','Remove infected leaves|Improve plant spacing|Apply an appropriate fungicide|Avoid overhead watering|Maintain field hygiene','Use disease-resistant varieties|Rotate crops|Keep leaves dry|Remove infected plant debris|Monitor plants regularly'),
dz('Tomato','Late Blight','High','A fast-spreading disease (Phytophthora infestans) that can destroy a field within days in cool, wet weather.','Water-soaked grey-green patches|White mold under leaves|Dark lesions on stems|Firm brown fruit rot','Oomycete infection|Cool wet nights|Dense canopy|Infected seed or tubers','Remove and destroy infected plants|Apply a protectant fungicide early|Improve drainage|Stop overhead irrigation','Plant certified disease-free stock|Space plants widely|Avoid wet foliage at night|Rotate with non-hosts'),
dz('Tomato','Leaf Mold','Moderate','A fungal disease (Passalora fulva) common in greenhouses and humid fields.','Pale yellow spots on upper leaves|Olive-green mold underneath|Curling leaves|Reduced yield','Humidity above 85%|Poor ventilation|Crowded plants','Increase airflow|Prune lower leaves|Apply a suitable fungicide|Reduce humidity','Grow resistant varieties|Ventilate greenhouses|Water at the base|Clean tools and supports'),
dz('Tomato','Septoria Leaf Spot','Moderate','A fungal disease (Septoria lycopersici) producing many small spots, usually after fruit set.','Small round spots with grey centres|Dark borders|Yellowing lower leaves|Leaf drop','Splashing rain|Infected debris|Warm wet weather','Remove spotted leaves|Apply a protectant fungicide|Mulch the soil|Water at the base','Rotate crops 2–3 years|Stake plants|Remove debris after harvest|Avoid working in wet fields'),
dz('Rice','Leaf Blast','High','A fungal disease (Magnaporthe oryzae) and one of the most damaging rice diseases worldwide.','Diamond-shaped spots with grey centres|Brown margins|Neck rot at heading|Empty grains','Excess nitrogen|Long leaf wetness|Cool nights with high humidity','Apply a recommended fungicide|Drain and reflood fields|Reduce nitrogen|Remove infected stubble','Use resistant varieties|Balanced fertilizer|Treat seed|Avoid late planting'),
dz('Rice','Brown Spot','Moderate','A fungal disease (Bipolaris oryzae) linked to poor soil fertility and stressed plants.','Oval brown spots with yellow halo|Spots on grains|Seedling blight|Patchy fields','Nutrient-poor soil|Water stress|Infected seed','Correct nutrient deficiencies|Treat with a suitable fungicide|Maintain water levels','Use clean seed|Apply potassium and silicon|Avoid drought stress|Burn or bury residue'),
dz('Rice','Bacterial Leaf Blight','High','A bacterial disease (Xanthomonas oryzae) that causes leaf drying and major yield loss.','Yellow-white stripes from leaf tips|Wavy lesion edges|Wilting seedlings|Milky ooze at dawn','Wounds from storms|Excess nitrogen|Infected irrigation water','Drain the field|Reduce nitrogen|Apply copper-based products as advised|Remove infected plants','Use resistant varieties|Clean seed|Avoid clipping seedlings|Control weeds near bunds'),
dz('Potato','Early Blight','Moderate','A fungal disease (Alternaria solani) affecting leaves and tubers of stressed plants.','Dark target-like spots|Yellow leaf margins|Sunken tuber lesions|Early defoliation','Plant stress|Warm humid weather|Infected debris','Remove infected foliage|Apply a fungicide on schedule|Irrigate in the morning|Fertilize adequately','Use certified seed|Rotate crops|Hill soil well|Destroy crop residue'),
dz('Potato','Late Blight','High','A devastating disease (Phytophthora infestans) that rots leaves and tubers quickly in cool, wet spells.','Water-soaked leaf lesions|White fuzzy growth|Black stems|Brown tuber rot','Cool wet weather|Infected seed tubers|Volunteer plants','Destroy infected plants|Apply a protectant fungicide|Delay harvest until vines die|Store tubers dry','Plant certified seed|Remove volunteers|Hill rows|Scout twice a week in wet weather'),
dz('Wheat','Leaf Rust','High','A fungal disease (Puccinia triticina) spread by wind-blown spores, lowering grain fill.','Orange-brown pustules on leaves|Yellowing|Shrivelled grain|Early leaf death','Mild humid weather|Susceptible varieties|Volunteer wheat','Apply a recommended fungicide|Scout flag leaves|Remove volunteer wheat','Grow resistant varieties|Sow on time|Avoid heavy nitrogen|Monitor regional alerts'),
dz('Wheat','Powdery Mildew','Moderate','A fungal disease (Blumeria graminis) that coats leaves with white powder in dense, shaded crops.','White powdery patches|Yellowing under patches|Black specks later|Stunted growth','Dense canopy|Cool humid weather|High nitrogen','Apply a suitable fungicide|Thin dense stands|Avoid excess nitrogen','Choose resistant varieties|Wider seed rate|Rotate crops|Remove stubble'),
dz('Maize','Northern Leaf Blight','Moderate','A fungal disease (Exserohilum turcicum) producing long cigar-shaped lesions.','Long grey-green lesions|Tan dried leaves|Reduced ear fill','Moderate temperatures|Heavy dew|Residue in field',"Apply a fungicide at early symptoms|Remove residue|Balance nutrition",FP),
dz('Cotton','Leaf Curl Virus','High','A whitefly-spread virus that curls leaves and stunts cotton plants.','Upward leaf curling|Thickened veins|Stunted plants|Few bolls','Whitefly vectors|Infected weeds|Late sowing','Control whiteflies|Remove infected plants|Remove weed hosts','Grow tolerant varieties|Sow early|Use yellow sticky traps|Scout weekly'),
dz('Chili','Anthracnose','Moderate','A fungal disease (Colletotrichum) causing sunken spots on ripening chili fruit.','Sunken dark fruit spots|Pinkish spore masses|Leaf spots|Dieback','Warm wet weather|Infected seed|Fruit injury','Pick and destroy infected fruit|Apply a suitable fungicide|Improve airflow','Use treated seed|Rotate crops|Avoid overhead irrigation|Harvest promptly')];
const HEALTHY={s:'None',d:'No disease patterns were detected. The plant looks healthy.',sy:['Uniform green leaves','No spots or lesions','Firm upright growth'],ca:['Good growing conditions'],tr:['No treatment needed','Continue regular watering and nutrition'],pv:['Scout weekly','Keep tools and field clean','Rotate crops each season']};
const find=(c,n)=>n==='Healthy'?HEALTHY:D.find(x=>x.c===c&&x.n===n)||HEALTHY;
const DAY=864e5,now=Date.now();
const seed=[['Tomato','Early Blight',92,.08],['Rice','Leaf Blast',88,1],['Potato','Healthy',96,2],['Wheat','Leaf Rust',91,3],['Chili','Healthy',97,4],['Tomato','Late Blight',85,6]].map((r,i)=>({id:'s'+i,crop:r[0],dis:r[1],conf:r[2],ts:now-r[3]*DAY,status:r[1]==='Healthy'?'Healthy':'Diseased',alts:[{n:'Other',p:100-r[2]}],seed:1,saved:i<3}));
let H=LS.get('cd_h',null);if(!H){H=seed;LS.set('cd_h',H)}
let N=LS.get('cd_n',null)||[{t:'Welcome to CropDoctor AI',ts:now-DAY,r:0},{t:'Crop health reminder: scan your fields weekly',ts:now-2*DAY,r:0}];
let P=LS.get('cd_p',{name:'Ravi Kumar',phone:'+91 98765 43210',email:'ravi@example.com',village:'Madhuranthagam',district:'Chengalpattu',state:'Tamil Nadu',size:'4.5',crops:'Tomato, Rice, Chili'});
let ST=LS.get('cd_s',{alerts:1,remind:1,tips:0,lang:'English'});
const ago=t=>{const m=(Date.now()-t)/6e4;return m<60?Math.max(1,m|0)+' min ago':m<1440?(m/60|0)+' hours ago':m<2880?'Yesterday':(m/1440|0)+' days ago'};
const fd=t=>new Date(t).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
const saveH=()=>LS.set('cd_h',H),saveN=()=>LS.set('cd_n',N);
function toast(m){const e=document.createElement('div');e.textContent=m;$('#toast').append(e);setTimeout(()=>e.remove(),3000)}
function notify(t){N.unshift({t,ts:Date.now(),r:0});saveN();badge()}
function badge(){const n=N.filter(x=>!x.r).length;$('#bd').textContent=n;$('#bd').style.display=n?'':'none'}
function applyTheme(t){document.documentElement.dataset.theme=t;$('#tb').textContent=t==='dark'?'🌙 Dark':'☀ Light';LS.set('cd_t',t)}
applyTheme(LS.get('cd_t',matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'));
/* ---------- AI (demo). Replace body with fetch('/api/predict',{method:'POST',body:formData}) later ---------- */
async function analyzeCropImage(file,crop){
 await new Promise(r=>setTimeout(r,1500));
 const c=crop==='Other'?CROPS[Math.random()*CROPS.length|0]:crop;
 const pool=D.filter(x=>x.c===c).map(x=>x.n).concat('Healthy');
 const top=pool[Math.random()*pool.length|0],conf=84+(Math.random()*13|0),rest=pool.filter(x=>x!==top).sort(()=>Math.random()-.5).slice(0,2);
 const a=Math.min(100-conf-1,2+(Math.random()*(100-conf-2)|0));
 return{crop:c,dis:top,conf,alts:[{n:top,p:conf},{n:rest[0],p:a},{n:rest[1],p:100-conf-a}],demo:true};
}
/* ---------- views ---------- */
const NAV=[['dash','🏠','Dashboard'],['scan','📷','AI Scanner'],['lib','📚','Disease Library'],['hist','🕘','Scan History'],['prof','👤','Profile'],['set','⚙️','Settings']];
let V='dash',L={q:'',c:'All'},HF={q:'',c:'All',s:'All'},S={};
function nav(){$('#nav').innerHTML=NAV.map(n=>`<button class="nb ${V===n[0]?'on':''}" data-a="go" data-i="${n[0]}"><span aria-hidden="true">${n[1]}</span>${n[2]}</button>`).join('');
 $('#bn').innerHTML=[0,1,2,3].map(i=>`<button class="${V===NAV[i][0]?'on':''}" data-a="go" data-i="${NAV[i][0]}"><span style="font-size:1.3rem">${NAV[i][1]}</span>${NAV[i][2].replace('AI ','').replace('Disease ','').replace('Scan ','')}</button>`).join('')+`<button data-a="menu"><span style="font-size:1.3rem">☰</span>More</button>`}
function go(v){V=v;$('#side').classList.remove('open');nav();$('#view').innerHTML=R[v]();$('#view').focus({preventScroll:true});scrollTo(0,0);if(v==='scan')renderPrev();if(v==='lib')libGrid();if(v==='hist')histRows()}
const th=e=>`<div class="th" aria-hidden="true">${e.img?`<img alt="" src="${e.img}">`:EM[e.crop]||'🌱'}</div>`;
const stats=()=>{const n=H.filter(x=>!x.seed);return{t:128+n.length,h:76+n.filter(x=>x.status==='Healthy').length,d:52+n.filter(x=>x.status!=='Healthy').length,s:H.filter(x=>x.saved).length+9}};
const R={
dash(){const s=stats(),hp=Math.round(s.h/s.t*100);
return`<section style="margin-top:8px"><div class="card hero"><div><h1>Your AI-powered crop health assistant</h1><p>Upload a photo of your crop leaf and let CropDoctor AI identify possible diseases and provide actionable treatment guidance.</p><div class="row"><button class="btn" data-a="go" data-i="scan">🔍 Scan a Crop</button><button class="btn o" data-a="go" data-i="lib">📚 Disease Library</button></div></div>
<svg class="leaf" viewBox="0 0 300 260" role="img" aria-label="Farmer scanning a leaf with an AI frame"><rect x="40" y="20" width="220" height="190" rx="18" fill="none" stroke="var(--g)" stroke-width="4" stroke-dasharray="14 8"/><path d="M150 40c70 20 90 90 40 140-60 10-110-40-90-100 15-25 35-35 50-40z" fill="var(--g)" opacity=".85"/><path d="M110 170c20-40 40-70 70-95" stroke="#fff" stroke-width="3" fill="none"/><circle cx="165" cy="105" r="9" fill="#a1470a"/><circle cx="140" cy="140" r="6" fill="#a1470a"/><rect x="40" y="105" width="220" height="4" fill="var(--g)"><animate attributeName="y" values="30;195;30" dur="3s" repeatCount="indefinite"/></rect><rect x="150" y="215" width="140" height="34" rx="17" fill="var(--card)" stroke="var(--g)"/><text x="165" y="237" font-size="14" font-weight="700" fill="var(--ink)">Early Blight 92%</text><text x="8" y="250" font-size="44">🧑‍🌾</text></svg></div></section>
<section><div class="grid g4"><div class="card stat"><b>${s.t}</b><span>Total Scans</span></div><div class="card stat"><b>${s.h}</b><span>Healthy Crops</span></div><div class="card stat"><b>${s.d}</b><span>Diseases Detected</span></div><div class="card stat"><b>${s.s}</b><span>Saved Reports · avg. confidence 91%</span></div></div></section>
<section><h2>Quick actions</h2><div class="grid g4">${[['scan','📷','Scan New Crop','Upload or capture a leaf'],['lib','📚','Disease Library','Browse symptoms and cures'],['hist','🕘','Scan History','Review past diagnoses'],['prof','🧑‍🌾','Farm Profile','Update your farm details']].map(q=>`<button class="qa" data-a="go" data-i="${q[0]}"><em>${q[1]}</em><b>${q[2]}</b><br><span>${q[3]}</span></button>`).join('')}</div></section>
<section><h2>Recent diagnoses</h2><div class="grid g3">${H.slice(0,4).map(e=>`<button class="card qa dg" data-a="view" data-i="${e.id}" style="width:100%">${th(e)}<div><b>${e.crop}</b><br>${e.dis}<br><small>${e.conf}% confidence · ${ago(e.ts)}</small></div></button>`).join('')}</div></section>
<section><h2>Crop health overview</h2><div class="grid g2c"><div class="card"><div class="bl"><span>Healthy crops</span><b>${hp}%</b></div><div class="bar top"><i style="width:${hp}%"></i></div><div class="bl"><span>Diseased crops</span><b>${100-hp}%</b></div><div class="bar"><i style="width:${100-hp}%;background:var(--bad);opacity:1"></i></div></div>
<div class="card"><b>Scans this week</b><div style="display:flex;gap:8px;align-items:end;height:90px;margin-top:10px">${[4,6,5,8,7,9,6].map((v,i)=>`<div style="flex:1;text-align:center;font-size:.75rem"><div style="height:${v*9}px;background:var(--g);border-radius:6px 6px 0 0"></div>${'MTWTFSS'[i]}</div>`).join('')}</div></div></div></section>`},
scan(){return`<section style="margin-top:8px"><h1 style="font-size:2rem">AI Crop Disease Scanner</h1><p style="color:var(--mut)">Upload a clear image of a crop leaf for the best diagnosis.</p>
<div class="card"><div class="drop" id="dz" tabindex="0" role="button" aria-label="Drop an image here or press Enter to browse"><big aria-hidden="true">🍃</big><b>Drag &amp; drop a leaf photo</b><p>JPG, JPEG, PNG · Maximum file size: 10 MB</p><div class="row" style="justify-content:center"><button class="btn" data-a="pick">Browse Image</button><button class="btn o" data-a="cam">📷 Capture with Camera</button></div></div>
<div id="pv" style="margin-top:16px"></div>
<div class="row" style="margin-top:16px;align-items:end"><label class="fld">Crop<select id="cs">${CROPS.concat('Other').map(c=>`<option ${S.crop===c?'selected':''}>${c}</option>`).join('')}</select></label><button class="btn" data-a="analyze">✨ Analyze with AI</button></div></div></section><section id="res"></section>`},
lib(){return`<section style="margin-top:8px"><h1 style="font-size:2rem">Crop Disease Library</h1><div class="row" style="margin:14px 0"><input class="sel" id="lq" type="search" placeholder="Search diseases..." aria-label="Search diseases" value="${esc(L.q)}" style="flex:1;min-width:200px"><select class="sel" id="lc" aria-label="Filter by crop">${['All'].concat(CROPS).map(c=>`<option ${L.c===c?'selected':''} value="${c}">${c==='All'?'All Crops':c}</option>`).join('')}</select></div><div class="grid g3" id="lg"></div></section>`},
hist(){return`<section style="margin-top:8px"><h1 style="font-size:2rem">Scan History</h1><div class="row" style="margin:14px 0"><input class="sel" id="hq" type="search" placeholder="Search history..." aria-label="Search history" value="${esc(HF.q)}" style="flex:1;min-width:180px"><select class="sel" id="hc" aria-label="Crop filter">${['All'].concat(CROPS).map(c=>`<option ${HF.c===c?'selected':''} value="${c}">${c==='All'?'All Crops':c}</option>`).join('')}</select><select class="sel" id="hs" aria-label="Status filter">${['All','Diseased','Healthy'].map(c=>`<option ${HF.s===c?'selected':''}>${c}</option>`).join('')}</select></div><div class="card" style="padding:8px"><table class="tbl"><thead><tr><th>Image</th><th>Crop</th><th>Diagnosis</th><th>Confidence</th><th>Date</th><th>Status</th><th>Action</th></tr></thead><tbody id="hb2"></tbody></table><p id="he" style="padding:16px;color:var(--mut)" hidden>No scans match. Try another filter or scan a crop.</p></div></section>`},
prof(){const s=stats(),f=[['name','Farmer Name'],['phone','Phone Number'],['email','Email'],['village','Village'],['district','District'],['state','State'],['size','Farm Size (acres)'],['crops','Primary Crops']];
return`<section style="margin-top:8px"><h1 style="font-size:2rem">Farmer Profile</h1><div class="grid g4" style="margin:14px 0"><div class="card stat"><b>${esc(P.size)||0}</b><span>Total Farm Area (acres)</span></div><div class="card stat"><b>${P.crops.split(',').filter(x=>x.trim()).length}</b><span>Number of Crops</span></div><div class="card stat"><b>${s.t}</b><span>Total Scans</span></div><div class="card stat"><b>${s.d}</b><span>Diseased Crops</span></div></div><div class="card"><div class="grid g2c">${f.map(x=>`<label class="fld">${x[1]}<input id="p_${x[0]}" value="${esc(P[x[0]])}"></label>`).join('')}</div><button class="btn" style="margin-top:18px" data-a="saveprof">Update Profile</button></div></section>`},
set(){const t=(k,l)=>`<label class="tg">${l}<input type="checkbox" data-k="${k}" ${ST[k]?'checked':''}></label>`;
return`<section style="margin-top:8px"><h1 style="font-size:2rem">Settings</h1><div class="grid g2c" style="margin-top:14px"><div class="card"><h3>Account Settings</h3><div class="row" style="margin-top:12px"><button class="btn o sm" data-a="go" data-i="prof">Edit profile</button><button class="btn o sm" data-a="pw">Change password</button></div></div>
<div class="card"><h3>Notification Settings</h3>${t('alerts','Disease alerts')}${t('remind','Scan reminders')}${t('tips','Farming tips')}</div>
<div class="card"><h3>Appearance</h3><div class="row" style="margin-top:12px"><button class="btn o sm" data-a="setth" data-i="light">☀ Light mode</button><button class="btn o sm" data-a="setth" data-i="dark">🌙 Dark mode</button></div></div>
<div class="card"><h3>Language</h3><select class="sel" id="lang" aria-label="Language" style="margin-top:12px">${['English','Telugu','Tamil','Hindi'].map(l=>`<option ${ST.lang===l?'selected':''}>${l}</option>`).join('')}</select></div>
<div class="card"><h3>Privacy</h3><div class="row" style="margin-top:12px"><button class="btn d sm" data-a="clrh">Clear scan history</button><button class="btn d sm" data-a="clra">Clear application data</button></div></div></div></section>`}};
function libGrid(){const q=L.q.toLowerCase(),l=D.filter(d=>(L.c==='All'||d.c===L.c)&&(d.n+d.c).toLowerCase().includes(q));
 $('#lg').innerHTML=l.map(d=>`<article class="card"><div class="dg"><div class="th" aria-hidden="true">${EM[d.c]}</div><div><h3>${d.n}</h3><span class="pill ${d.s==='High'?'bad':''}">${d.c} · ${d.s} severity</span></div></div><p style="color:var(--mut);font-size:.92rem"><b>Symptoms:</b> ${d.sy.slice(0,2).join(', ')}.<br><b>Treatment:</b> ${d.tr[0]}.<br><b>Prevention:</b> ${d.pv[0]}.</p><button class="btn sm" data-a="detail" data-i="${D.indexOf(d)}">View Details</button></article>`).join('')||'<p>No diseases found. Try a different search or crop.</p>'}
function histRows(){const q=HF.q.toLowerCase(),l=H.filter(e=>(HF.c==='All'||e.crop===HF.c)&&(HF.s==='All'||e.status===HF.s)&&(e.crop+e.dis).toLowerCase().includes(q));
 $('#hb2').innerHTML=l.map(e=>`<tr><td data-l="Image">${th(e)}</td><td data-l="Crop">${e.crop}</td><td data-l="Diagnosis">${e.dis}</td><td data-l="Confidence">${e.conf}%</td><td data-l="Date">${fd(e.ts)}</td><td data-l="Status"><span class="pill ${e.status==='Healthy'?'':'bad'}">${e.status}</span></td><td data-l="Action"><span class="row"><button class="btn sm" data-a="view" data-i="${e.id}">View report</button><button class="btn d sm" data-a="del" data-i="${e.id}" aria-label="Delete scan">🗑</button></span></td></tr>`).join('');$('#he').hidden=!!l.length}
function renderPrev(){const p=$('#pv');if(!S.url){p.innerHTML='';return}p.innerHTML=`<div class="prev"><img src="${S.url}" alt="Selected crop leaf preview"><div><b>${esc(S.name)}</b><br><small>${S.size}</small><br><button class="btn d sm" style="margin-top:10px" data-a="rm">Remove image</button></div></div>`}
/* ---------- results ---------- */
const lst=(t,a)=>`<div class="card"><h3>${t}</h3><ul class="l">${a.map(x=>`<li>${x}</li>`).join('')}</ul></div>`;
function result(e){const d=find(e.crop,e.dis),h=e.dis==='Healthy',al=(e.alts||[]).filter(a=>a.n!=='Other');
return`<div class="card" id="rc"><div class="row" style="justify-content:space-between"><h2>AI Diagnosis Result</h2><span class="demo">Demo AI Analysis</span></div>
<div class="rh" style="margin:18px 0"><div class="ring" style="--p:0" data-p="${e.conf}" role="img" aria-label="Confidence ${e.conf} percent"><b>${e.conf}%</b></div><dl><dt>Crop</dt><dd>${e.crop}</dd><dt>Disease</dt><dd>${e.dis}</dd><dt>Status</dt><dd><span class="pill ${h?'':'bad'}">${h?'Healthy':'Disease Detected'}</span></dd><dt>AI Confidence</dt><dd>${e.conf}%</dd></dl></div>
${al.length?`<h3>Possible diseases</h3>${al.map((a,i)=>`<div class="bl"><span>${i?'':'<b>'}${a.n}${i?'':'</b> ★'}</span><span>${a.p}%</span></div><div class="bar ${i?'':'top'}"><i style="width:${a.p}%"></i></div>`).join('')}`:''}
<p style="color:var(--mut)">${d.d||''}</p>
<div class="grid g2c" style="margin-top:16px">${lst('Symptoms',d.sy)}${lst('Possible Causes',d.ca)}${lst('Treatment',d.tr)}${lst('Prevention',d.pv)}</div>
<div class="row" style="margin-top:18px"><button class="btn" data-a="print" data-i="${e.id}">⬇ Download Report</button><button class="btn o" data-a="save" data-i="${e.id}">${e.saved?'✔ Saved':'💾 Save Diagnosis'}</button><button class="btn o" data-a="share" data-i="${e.id}">Share Report</button><button class="btn o" data-a="again">Scan Another Crop</button></div>
<div class="disc">AI-generated diagnosis is an indication only. Consult an agricultural expert before applying chemical treatments.</div></div>`}
function ring(){setTimeout(()=>document.querySelectorAll('.ring[data-p]').forEach(r=>r.style.setProperty('--p',r.dataset.p)),60)}
function report(e){const d=find(e.crop,e.dis),ul=a=>`<ul>${a.map(x=>`<li>${x}</li>`).join('')}</ul>`;
$('#report').innerHTML=`<h1>CropDoctor AI</h1><h2>AI Crop Disease Diagnosis Report</h2><p><b>Date:</b> ${fd(e.ts)}<br><b>Crop:</b> ${e.crop}<br><b>Disease:</b> ${e.dis}<br><b>Confidence:</b> ${e.conf}%<br><i>Demo AI Analysis – simulated result</i></p><h3>Symptoms</h3>${ul(d.sy)}<h3>Treatment</h3>${ul(d.tr)}<h3>Prevention</h3>${ul(d.pv)}<p><b>Disclaimer:</b> AI-generated diagnosis is for informational purposes only.</p>`;
setTimeout(()=>print(),100)}
/* ---------- modal / camera ---------- */
let stream=null;
function closeM(){stream&&stream.getTracks().forEach(t=>t.stop());stream=null;document.querySelectorAll('.ov').forEach(o=>o.remove())}
function modal(h){closeM();const o=document.createElement('div');o.className='ov';o.innerHTML=`<div class="md" role="dialog" aria-modal="true"><button class="x" data-a="close" aria-label="Close">✕</button>${h}</div>`;document.body.append(o);o.querySelector('button.x').focus();return o}
function detailHTML(d){return`<h2 style="padding-right:40px">${d.n}</h2><p><span class="pill ${d.s==='High'?'bad':''}">${d.c} · ${d.s} severity</span></p><p>${d.d}</p><div class="grid g2c">${lst('Symptoms',d.sy)}${lst('Causes',d.ca)}${lst('Treatment',d.tr)}${lst('Prevention',d.pv)}</div>${lst('Recommended farming practices',['Scout fields weekly, especially after rain','Use clean tools and certified seed','Keep a record of treatments and dates'])}<button class="btn" style="margin-top:16px" data-a="scanfor" data-i="${d.c}">Start AI Scan</button>`}
async function openCam(){if(!navigator.mediaDevices?.getUserMedia)return toast('Camera is not supported in this browser. Use Browse Image instead.');
 try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});modal(`<h2>Capture with Camera</h2><video id="vd" autoplay playsinline muted style="width:100%;border-radius:14px;margin:12px 0;background:#000"></video><img id="cp" alt="Captured photo" style="width:100%;border-radius:14px;margin:12px 0" hidden><div class="row"><button class="btn" data-a="snap">Capture</button><button class="btn o" data-a="retake" hidden>Retake</button><button class="btn" data-a="usephoto" hidden>Use Photo</button></div>`);stream=s;$('#vd').srcObject=s}
 catch{toast('Camera permission denied. Allow camera access or browse for an image.')}}
/* ---------- files ---------- */
function setFile(f){if(!f)return;if(!/^image\/(jpeg|png)$/.test(f.type))return toast('Unsupported file. Choose a JPG, JPEG or PNG image.');if(f.size>10485760)return toast('File is larger than 10 MB. Choose a smaller image.');
 const r=new FileReader();r.onload=()=>{S={...S,file:f,url:r.result,name:f.name,size:f.size>1048576?(f.size/1048576).toFixed(2)+' MB':Math.ceil(f.size/1024)+' KB'};renderPrev()};r.readAsDataURL(f)}
const thumb=u=>new Promise(r=>{const i=new Image();i.onload=()=>{const c=document.createElement('canvas');c.width=c.height=80;const x=c.getContext('2d'),m=Math.min(i.width,i.height);x.drawImage(i,(i.width-m)/2,(i.height-m)/2,m,m,0,0,80,80);r(c.toDataURL('image/jpeg',.6))};i.onerror=()=>r('');i.src=u});
async function analyze(){if(!S.url)return toast('Add a leaf image first.');S.crop=$('#cs').value;
 const o=modal(`<div style="text-align:center;padding:10px"><div class="scan"><img src="${S.url}" alt=""></div><h3 id="lm">Analyzing crop image...</h3><div class="bar top" style="margin:16px 0 6px"><i id="lp" style="width:0;background:var(--g);opacity:1"></i></div><small>Demo AI Analysis</small></div>`);o.querySelector('.x').remove();
 const msgs=['Analyzing crop image...','Detecting leaf patterns...','Comparing disease characteristics...','Generating diagnosis...'];let k=0;const iv=setInterval(()=>{k=Math.min(k+1,3);$('#lm').textContent=msgs[k];$('#lp').style.width=(k+1)*25+'%'},800);setTimeout(()=>{const p=$('#lp');p&&(p.style.width='20%')},50);
 const [r]=await Promise.all([analyzeCropImage(S.file,S.crop),new Promise(r=>setTimeout(r,3300))]);clearInterval(iv);
 const e={id:'n'+Date.now(),crop:r.crop,dis:r.dis,conf:r.conf,ts:Date.now(),status:r.dis==='Healthy'?'Healthy':'Diseased',alts:r.alts,img:await thumb(S.url),saved:false};
 H.unshift(e);try{saveH()}catch{}notify('New scan completed');notify(e.dis==='Healthy'?`${e.crop} looks healthy`:`${e.dis} detected in ${e.crop}`);notify('Your scan report is ready');
 closeM();$('#res').innerHTML=result(e);ring();$('#rc').scrollIntoView({behavior:'smooth'});toast('Diagnosis ready')}
/* ---------- events ---------- */
const byId=i=>H.find(e=>e.id===i);
const A={
go:i=>go(i),menu:()=>$('#side').classList.toggle('open'),theme:()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'),setth:i=>{applyTheme(i);toast(i+' mode on')},
bell:()=>{const d=$('#nd');d.innerHTML=N.slice(0,8).map(n=>`<div>${n.r?'':'● '}${esc(n.t)}<br><small>${ago(n.ts)}</small></div>`).join('');d.classList.toggle('open');N.forEach(n=>n.r=1);saveN();badge()},
pick:()=>$('#fi').click(),cam:openCam,rm:()=>{S={crop:S.crop};renderPrev()},analyze,close:closeM,
snap:()=>{const v=$('#vd'),c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);S.cap=c.toDataURL('image/jpeg',.9);$('#cp').src=S.cap;$('#cp').hidden=false;v.hidden=true;document.querySelectorAll('[data-a=snap]').forEach(b=>b.hidden=true);document.querySelectorAll('[data-a=retake],[data-a=usephoto]').forEach(b=>b.hidden=false)},
retake:()=>{$('#cp').hidden=true;$('#vd').hidden=false;document.querySelectorAll('[data-a=snap]').forEach(b=>b.hidden=false);document.querySelectorAll('[data-a=retake],[data-a=usephoto]').forEach(b=>b.hidden=true)},
usephoto:async()=>{const b=await (await fetch(S.cap)).blob();closeM();setFile(new File([b],'camera-photo.jpg',{type:'image/jpeg'}))},
detail:i=>modal(detailHTML(D[i])),scanfor:c=>{closeM();S.crop=c;go('scan')},again:()=>{S={};go('scan');toast('Ready for a new scan')},
view:i=>{const e=byId(i);if(e)modal(result(e));ring()},
save:i=>{const e=byId(i);e.saved=true;saveH();document.querySelectorAll(`[data-a=save][data-i="${i}"]`).forEach(b=>b.textContent='✔ Saved');toast('Diagnosis saved')},
del:i=>{H=H.filter(e=>e.id!==i);saveH();histRows();toast('Scan deleted')},
print:i=>report(byId(i)),share:async i=>{const e=byId(i),t=`CropDoctor AI: ${e.crop} – ${e.dis} (${e.conf}% confidence, demo analysis)`;try{if(navigator.share)await navigator.share({title:'CropDoctor AI report',text:t});else{await navigator.clipboard.writeText(t);toast('Report summary copied')}}catch{toast('Sharing cancelled')}},
saveprof:()=>{['name','phone','email','village','district','state','size','crops'].forEach(k=>P[k]=$('#p_'+k).value.trim());LS.set('cd_p',P);toast('Profile updated');go('prof')},
pw:()=>modal(`<h2>Change password</h2><div class="grid" style="margin-top:12px"><label class="fld">New password<input id="np" type="password" minlength="6"></label><label class="fld">Confirm password<input id="cp2" type="password"></label><button class="btn" data-a="pwok">Save password</button><small>Demo: no account server yet, nothing is stored.</small></div>`),
pwok:()=>{const a=$('#np').value;if(a.length<6)return toast('Use at least 6 characters.');if(a!==$('#cp2').value)return toast('Passwords do not match.');closeM();toast('Password updated (demo)')},
clrh:()=>{if(confirm('Delete all scan history?')){H=[];saveH();toast('Scan history cleared')}},
clra:()=>{if(confirm('Clear all CropDoctor data on this device?')){['cd_h','cd_n','cd_p','cd_s','cd_t'].forEach(LS.del);location.reload()}}};
document.addEventListener('click',e=>{const b=e.target.closest('[data-a]');if(!e.target.closest('.dd,.sw,[data-a=bell]')){document.querySelectorAll('.dd').forEach(d=>d.classList.remove('open'))}
 if(b){A[b.dataset.a]?.(b.dataset.i);if(b.closest('#sr')){$('#sr').classList.remove('open');$('#gs').value=''}}
 else if(e.target.classList.contains('ov'))closeM()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeM();if(e.key==='Enter'&&e.target.id==='dz')A.pick()});
document.addEventListener('change',e=>{const t=e.target;if(t.id==='fi'){setFile(t.files[0]);t.value=''}
 else if(t.id==='lc'){L.c=t.value;libGrid()}else if(t.id==='hc'){HF.c=t.value;histRows()}else if(t.id==='hs'){HF.s=t.value;histRows()}
 else if(t.id==='lang'){ST.lang=t.value;LS.set('cd_s',ST);toast('Language saved: '+t.value)}else if(t.dataset.k){ST[t.dataset.k]=t.checked?1:0;LS.set('cd_s',ST);toast('Setting saved')}else if(t.id==='cs')S.crop=t.value});
document.addEventListener('input',e=>{const t=e.target;if(t.id==='lq'){L.q=t.value;libGrid()}else if(t.id==='hq'){HF.q=t.value;histRows()}
 else if(t.id==='gs'){const q=t.value.trim().toLowerCase(),r=$('#sr');if(!q){r.classList.remove('open');return}
  const ds=D.filter(d=>(d.n+d.c).toLowerCase().includes(q)).slice(0,5).map(d=>`<button data-a="detail" data-i="${D.indexOf(d)}">🦠 ${d.n} <small>${d.c} · disease</small></button>`),
  cs=CROPS.filter(c=>c.toLowerCase().includes(q)).map(c=>`<button data-a="lcrop" data-i="${c}">${EM[c]} ${c} <small>crop · browse diseases</small></button>`),
  hs=H.filter(h=>(h.crop+h.dis).toLowerCase().includes(q)).slice(0,4).map(h=>`<button data-a="view" data-i="${h.id}">🕘 ${h.crop} – ${h.dis} <small>scan · ${fd(h.ts)}</small></button>`);
  r.innerHTML=[...ds,...cs,...hs].join('')||'<div>No matches found.</div>';r.classList.add('open')}});
A.lcrop=c=>{L={q:'',c};go('lib')};
document.addEventListener('dragover',e=>{const z=e.target.closest('#dz');if(z){e.preventDefault();z.classList.add('over')}});
document.addEventListener('dragleave',e=>e.target.closest&&e.target.closest('#dz')?.classList.remove('over'));
document.addEventListener('drop',e=>{const z=e.target.closest('#dz');if(z){e.preventDefault();z.classList.remove('over');setFile(e.dataTransfer.files[0])}});
badge();go('dash');