const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],A=$('#app');
const inr=n=>'₹'+Math.round(n).toLocaleString('en-IN');
const NAV=[['','Home'],['find','Find Machinery'],['list','List Resource'],['community','Community'],['bookings','My Bookings'],['messages','Messages'],['profile','Profile']];
const TAB=[['','🏠','Home'],['find','🔍','Search'],['bookings','📅','Bookings'],['messages','💬','Messages'],['profile','👤','Profile']];
const F={q:'',cat:'',max:5000,op:0,del:0,sort:'rec'};let tab='Upcoming',chat=0,step=1,bk={s:'',e:'',op:0,del:0},draft={};
function toast(m,err){const t=$('#toast');t.textContent=(err?'⚠️ ':'✅ ')+m;t.className='on'+(err?' err':'');setTimeout(()=>t.className='',2600)}
function modal(h){const m=$('#modal');m.innerHTML=h?`<div class="mbox">${h}</div>`:'';m.className=h?'on':''}
$('#modal').onclick=e=>{if(e.target.id=='modal')modal()};
const trust=r=>Math.min(99,Math.round(r.rating*18+r.hours/100));
const cond=c=>({Excellent:'🟢',Good:'🟢',Fair:'🟡'}[c]||'🔴')+' '+c;
function card(r){return`<article class="card"><div class="img" style="background:${r.bg}">${r.emoji}<button class="fav" data-fav="${r.id}" aria-label="Save">${S.fav.has(r.id)?'❤️':'♡'}</button></div><div class="cb"><h3>${r.name}</h3><div class="meta">${r.cat} · ${r.owner} ✔️ Verified</div><div class="row meta"><span>⭐ ${r.rating}</span><span>📍 ${r.dist} km</span><span>${cond(r.cond)}</span></div><div class="row">${r.op?'<span class="tag">👨‍🌾 Operator</span>':''}${r.del?'<span class="tag">🚚 Delivery</span>':''}</div><div class="row sp" style="margin-top:auto"><span class="price">${inr(r.price)}<small>/${r.unit}</small></span></div><div class="row"><a class="btn ghost sm" href="#/res/${r.id}">View Details</a><a class="btn sm" href="#/res/${r.id}">Book Now</a></div></div></article>`}
const P={};
P.home=()=>`<section class="hero"><h1>Your Farm. Your Community. Your Resources.</h1><p>Find, rent and share agricultural machinery with farmers near you.</p><a class="btn y" href="#/find">Find Machinery</a> <a class="btn ghost" style="color:#fff;border-color:#fff" href="#/list">List Your Equipment</a></section>
<form class="sb" id="hs"><input id="hq" placeholder="What do you need?"><select id="hl"><option>Chengalpattu</option>${LOC.slice(1).map(l=>`<option>${l}</option>`).join('')}</select><input type="date" aria-label="Date"><select id="hc"><option value="">All categories</option>${CATS.map(c=>`<option>${c[1]}</option>`).join('')}</select><button class="btn">Search Resources</button></form>
<div class="stats">${[['2450','Farmers'],['1280','Resources'],['3850','Completed Rentals'],['18.5','Estimated Farmer Savings']].map(s=>`<div class="stat"><b data-n="${s[0]}">0</b>${s[1]}</div>`).join('')}</div>
<h2 class="sec">Browse by category</h2><div class="cats">${CATS.map(c=>`<div class="cat" data-cat="${c[1]}"><span>${c[0]}</span><h3>${c[1]}</h3><p>${RES.filter(r=>r.cat==c[1]).length*14+20} available</p><a class="tag">View</a></div>`).join('')}</div>
<h2 class="sec">🤖 FarmLink SmartMatch</h2><div class="panel"><p class="sub">Describe what you need and we'll match it.</p><div class="row" style="margin-top:10px"><input id="sm" style="flex:1;min-width:220px" value="I need to harvest 5 acres of paddy next week."><button class="btn" id="smb">Find match</button></div><div id="smr"></div></div>
<h2 class="sec">Weather-aware booking</h2><div class="panel row sp"><div>⚠️ <b>Rain expected tomorrow.</b><br><span class="sub">Your tractor booking is scheduled tomorrow at 10 AM.</span></div><div class="row"><button class="btn sm" data-t="Booking kept">Keep Booking</button><button class="btn ghost sm" data-t="Reschedule request sent">Reschedule</button></div></div>
<h2 class="sec">Nearby resources</h2><div class="panel" style="background:#dfead0;position:relative;height:260px;overflow:hidden">${[['📍 Your Farm',50,50],['🚜 2.4 km',25,30],['💧 3.1 km',70,25],['🌾 5.6 km',30,72],['🌱 7.2 km',78,68]].map(m=>`<span class="tag" style="position:absolute;left:${m[1]}%;top:${m[2]}%;background:#fff;font-size:14px">${m[0]}</span>`).join('')}</div>
<h2 class="sec">Popular near you</h2><div class="grid">${RES.slice(0,4).map(card).join('')}</div>`;
P.find=()=>`<div class="layout"><aside class="panel"><h3>Filters</h3><label>Search</label><input id="fq" value="${F.q}" placeholder="Search tractors, harvesters, pumps…"><label>Category</label><select id="fc"><option value="">All</option>${CATS.map(c=>`<option ${F.cat==c[1]?'selected':''}>${c[1]}</option>`).join('')}</select><label>Max price: ${inr(F.max)}</label><input type="range" id="fp" min="100" max="5000" step="100" value="${F.max}"><label class="chk"><input type="checkbox" id="fo" ${F.op?'checked':''}>Operator available</label><label class="chk"><input type="checkbox" id="fd" ${F.del?'checked':''}>Delivery available</label><label>Sort by</label><select id="fs">${[['rec','Recommended'],['near','Nearest'],['low','Lowest price'],['rate','Highest rating'],['pop','Most popular']].map(o=>`<option value="${o[0]}" ${F.sort==o[0]?'selected':''}>${o[1]}</option>`).join('')}</select></aside><section><div class="sub" id="cnt"></div><div class="grid" id="res"></div></section></div>`;
function runFind(){let l=RES.filter(r=>(!F.q||(r.name+r.cat).toLowerCase().includes(F.q.toLowerCase()))&&(!F.cat||r.cat==F.cat)&&r.price<=F.max&&(!F.op||r.op)&&(!F.del||r.del));
const k={rec:r=>-r.rating*10+r.dist,near:r=>r.dist,low:r=>r.price,rate:r=>-r.rating,pop:r=>-r.pop};l.sort((a,b)=>k[F.sort](a)-k[F.sort](b));
$('#cnt').textContent=l.length+' resources found';$('#res').innerHTML=l.length?l.map(card).join(''):'<div class="empty" style="grid-column:1/-1"><span>🔎</span><h3>No matches</h3><p class="sub">Try widening your filters.</p></div>'}
function days(r){let h='<div class="cal">'+'SMTWTFS'.split('').map(d=>`<div class="h">${d}</div>`).join('')+'<div class="h"></div>'.repeat(3);
for(let d=1;d<=31;d++)h+=`<div class="${r.booked.includes(d)?'bk':r.pending.includes(d)?'pd':''} ${bk.s==d||bk.e==d?'sel':''}" data-d="${d}">${d}</div>`;return h+'</div><p class="meta" style="margin-top:8px">🟢 Available · 🔴 Booked · 🟡 Pending (October 2026)</p>'}
function calc(r){const n=bk.s?(bk.e?Math.abs(bk.e-bk.s)+1:1):0,u=r.unit=='hour'?8:r.unit=='acre'?5:1,base=r.price*u*Math.max(n,1),op=bk.op?1000:0,dl=bk.del?500:0;return{n,u,base,op,dl,tot:n?base+op+dl:0}}
P.res=id=>{const r=RES.find(x=>x.id==id);if(!r)return P.find();const c=calc(r);return`<a class="sub" href="#/find">← Back</a><div class="two"><div><div class="img panel" style="background:${r.bg};height:260px;font-size:110px">${r.emoji}</div><h2 class="sec" style="margin-top:20px">${r.name}</h2><div class="row"><span class="tag">⭐ ${r.rating}</span><span class="tag">${cond(r.cond)}</span><span class="tag">✔️ Verified Equipment</span><span class="tag y">Trust ${trust(r)}</span></div><p class="meta" style="margin:10px 0">Owner: ${r.owner} · 📍 ${r.loc} (${r.dist} km)</p><div class="panel"><table>${[['Brand',r.brand],['Year',r.year],['Engine hours',r.hours],['Last service','12 Aug 2026'],['Previous repairs','Hydraulic seal (2025)']].map(x=>`<tr><td class="sub">${x[0]}</td><td>${x[1]}</td></tr>`).join('')}</table></div><h3 style="margin:20px 0 8px">Before / after inspection</h3><div class="row"><div class="panel">Before: 📷📷📷 uploaded</div><div class="panel">After: awaiting return</div><button class="btn red sm" data-report>Report Damage</button></div><h3 style="margin:20px 0 8px">Reviews</h3>${REVIEWS.map(v=>`<div class="panel" style="margin-bottom:8px"><b>${v[0]}</b> ${'⭐'.repeat(v[1])}<br>${v[2]}</div>`).join('')}</div>
<aside class="panel" style="align-self:start;position:sticky;top:80px"><div class="price">${inr(r.price)}<small>/${r.unit}</small></div><h3 style="margin:12px 0 6px">Select dates</h3>${days(r)}<div class="row" style="margin:12px 0"><input type="time" value="08:00" aria-label="Start time" style="flex:1"><input type="time" value="16:00" aria-label="End time" style="flex:1"></div>
<label class="chk"><input type="checkbox" id="bo" ${bk.op?'checked':''} ${r.op?'':'disabled'}>Operator (+₹1,000)</label><label class="chk"><input type="checkbox" id="bd" ${bk.del?'checked':''} ${r.del?'':'disabled'}>Delivery (+₹500)</label>
<table style="margin-top:8px"><tr><td>${c.n||0} day(s) × ${c.u>1?c.u+' '+r.unit+'s × ':''}${inr(r.price)}</td><td align="right">${inr(c.base*(c.n?1:0))}</td></tr><tr><td>Operator</td><td align="right">${inr(c.op)}</td></tr><tr><td>Delivery</td><td align="right">${inr(c.dl)}</td></tr><tr class="tot"><td>Total</td><td align="right">${inr(c.tot)}</td></tr></table>
<button class="btn" style="width:100%;margin:8px 0" data-book="${r.id}">Send Booking Request</button><button class="btn ghost" style="width:100%" data-msg>Message Owner</button><p class="meta" style="margin-top:8px">🔒 Secure payment</p></aside></div>`};
P.bookings=()=>{const l=S.bookings.filter(b=>b.status==tab);return`<h2 class="sec">My Bookings</h2><div class="tabs">${['Upcoming','Active','Completed','Cancelled','Saved'].map(t=>`<button class="${t==tab?'on':''}" data-tab="${t}">${t}</button>`).join('')}</div>`+(tab=='Saved'?(S.fav.size?`<div class="grid">${RES.filter(r=>S.fav.has(r.id)).map(card).join('')}</div>`:`<div class="empty"><span>♡</span><h3>No saved resources</h3><a class="btn" href="#/find">Browse machinery</a></div>`):l.length?`<div class="grid">${l.map(b=>{const r=RES.find(x=>x.id==b.rid);return`<div class="card"><div class="cb"><h3>${r.emoji} ${r.name}</h3><div class="meta">${r.owner} · ${b.date} · ${b.time}</div><div class="row sp"><b>${inr(b.amt)}</b><span class="tag ${b.status=='Cancelled'?'r':b.status=='Upcoming'?'y':''}">${b.status}</span></div><div class="row"><a class="btn ghost sm" href="#/res/${r.id}">Details</a><button class="btn ghost sm" data-msg>Message</button>${b.status=='Upcoming'?`<button class="btn ghost sm" data-resched>Reschedule</button><button class="btn red sm" data-cancel="${b.id}">Cancel</button>`:''}${b.status=='Completed'?`<button class="btn y sm" data-review="${b.rid}">Review</button>`:''}</div></div></div>`}).join('')}</div>`:`<div class="empty"><span>📅</span><h3>No ${tab.toLowerCase()} bookings</h3><p class="sub">Find equipment for your next job.</p><a class="btn" href="#/find">Find Machinery</a></div>`)};
P.list=()=>{const st=['Category','Details','Photos','Pricing','Availability','Services','Location'];return`<h2 class="sec">List a resource</h2><div class="panel" style="max-width:640px"><div class="bar"><i style="width:${step/7*100}%"></i></div><p class="sub" style="margin:8px 0">Step ${step} of 7 – ${st[step-1]}</p>${[
`<select id="d_cat">${CATS.map(c=>`<option>${c[1]}</option>`).join('')}</select>`,
`<label>Name</label><input id="d_name" value="${draft.name||''}"><label>Brand / model / year</label><input id="d_b" placeholder="Mahindra 575, 2019"><label>Condition</label><select><option>Excellent</option><option>Good</option><option>Fair</option></select><label>Description</label><textarea></textarea>`,
`<div class="empty"><span>📷</span><p>Drop equipment photos here</p><input type="file" multiple accept="image/*"></div>`,
`<label>Price per hour (₹)</label><input id="d_p" type="number" value="${draft.price||''}"><label>Per day (₹)</label><input type="number"><label>Per acre (₹)</label><input type="number">`,
`<p>Mark days when this is available.</p>${days({booked:[],pending:[]})}`,
`<label class="chk"><input type="checkbox">Operator available</label><label class="chk"><input type="checkbox">Delivery available</label>`,
`<label>Village / town</label><select>${LOC.map(l=>`<option>${l}</option>`).join('')}</select>`][step-1]}<div class="row sp" style="margin-top:16px">${step>1?'<button class="btn ghost" data-step="-1">Back</button>':'<span></span>'}${step<7?'<button class="btn" data-step="1">Next</button>':'<button class="btn y" data-publish>Publish Resource</button>'}</div></div>`};
P.community=()=>`<h2 class="sec">🌾 Community Resource Pool</h2><div class="grid">${S.comm.map((c,i)=>`<div class="card"><div class="cb"><h3>${c.n}</h3><div class="meta">${c.members} members</div><div class="row"><span class="tag">🚜 ${c.t}</span><span class="tag">🌾 ${c.h}</span><span class="tag">💧 ${c.p}</span></div><div class="meta">Utilization ${60+i*3}%</div><div class="bar"><i style="width:${60+i*3}%"></i></div><div class="row"><button class="btn sm ${c.joined?'ghost':''}" data-join="${i}">${c.joined?'Joined ✓':'Join Community'}</button><a class="btn ghost sm" href="#/find">View Shared Resources</a><button class="btn ghost sm" data-t="Post created">Create Post</button></div></div></div>`).join('')}</div>`;
P.messages=()=>{const c=S.chats[chat];return`<div class="chat"><div class="panel"><input placeholder="Search" aria-label="Search chats">${S.chats.map((x,i)=>`<div class="conv ${i==chat?'on':''}" data-chat="${i}"><b>${x.n}</b> <span class="tag">● online</span><div class="meta">${x.m.at(-1)[1]}</div></div>`).join('')}</div><div class="panel" style="display:flex;flex-direction:column"><div class="row sp"><b>${c.n}</b><span class="tag">🚜 Mahindra 575 · Pending booking</span></div><div class="msgs">${c.m.map(m=>`<div class="bub ${m[0]}">${m[1]}</div>`).join('')}</div><form class="row" id="cf"><input id="ci" style="flex:1" placeholder="Type a message"><button class="btn">Send</button></form></div></div>`};
P.profile=()=>`<div class="two"><div class="panel"><div style="font-size:64px">🧑‍🌾</div><h2 id="pn">${S.name||'Ravi Kumar'}</h2><p class="meta">Chengalpattu · 6 acres · Paddy, groundnut</p><div class="row"><span class="tag">✔️ Verified Farmer</span><span class="tag">⭐ 4.9</span></div><h3 style="margin:16px 0 4px">FarmLink Trust Score: 96</h3><div class="bar"><i style="width:96%"></i></div><p class="meta">28 successful rentals · 0 late returns</p><div class="row" style="margin-top:12px"><button class="btn" data-edit>Edit Profile</button><button class="btn ghost" data-t="Verification submitted">Verification</button></div></div><div class="panel"><h3>Owner dashboard</h3><table>${[['Resources','4'],['Total bookings','37'],['Earnings','₹84,200'],['Avg rating','4.8']].map(x=>`<tr><td>${x[0]}</td><td align="right"><b>${x[1]}</b></td></tr>`).join('')}</table><a class="btn ghost" style="margin-top:10px" href="#/admin">Admin dashboard</a></div></div>`;
P.admin=()=>{const bars=a=>`<div class="cols">${a.map(v=>`<i style="height:${v}%" title="${v}"></i>`).join('')}</div>`;return`<h2 class="sec">Admin dashboard</h2><div class="stats">${[['Total Farmers','2,450'],['Verified','1,980'],['Active Listings','1,120'],['Active Bookings','184'],['Completed Rentals','3,850'],['Revenue','₹42.6L'],['Commission','₹2.1L']].map(s=>`<div class="stat"><b>${s[1]}</b>${s[0]}</div>`).join('')}</div><div class="charts">${[['Monthly bookings',[30,42,38,55,60,72,80]],['Monthly revenue',[25,35,40,48,58,66,90]],['Farmer growth',[20,30,45,52,64,78,88]],['Resource utilization',[50,58,62,60,70,74,79]]].map(c=>`<div class="panel"><h3>${c[0]}</h3>${bars(c[1])}</div>`).join('')}</div>`};
function render(){const [, p='', a]=location.hash.slice(1).split('/');const k=p||'home';A.innerHTML=(P[k]||P.home)(a);window.scrollTo(0,0);
$('#nav').innerHTML=NAV.map(n=>`<a href="#/${n[0]}" class="${n[0]==p?'on':''}">${n[1]}</a>`).join('');$('#nav').className='';$('#tabs').innerHTML=TAB.map(n=>`<a href="#/${n[0]}" class="${n[0]==p?'on':''}"><span>${n[1]}</span>${n[2]}</a>`).join('');$('#nb').textContent=S.notes.length;
if(k=='find')runFind();$$('[data-n]').forEach(e=>{const t=+e.dataset.n,d=t%1;let i=0;const f=setInterval(()=>{i+=.05;e.textContent=(e.dataset.n==18.5?'₹'+(t*Math.min(i,1)).toFixed(1)+'L+':Math.round(t*Math.min(i,1)).toLocaleString('en-IN')+'+');if(i>=1)clearInterval(f)},30)})}
function rep(){modal(`<h3>Report an issue</h3><label>Reason</label><select><option>Fake listing</option><option>Incorrect information</option><option>Damaged equipment</option><option>Unreliable owner</option><option>Suspicious user</option></select><label>Description</label><textarea id="rd"></textarea><label>Photo (optional)</label><input type="file"><div class="row" style="margin-top:12px"><button class="btn red" id="rs">Submit Report</button><button class="btn ghost" data-x>Cancel</button></div>`)}
function pay(id){const r=RES.find(x=>x.id==id),c=calc(r);modal(`<h3>Payment</h3><p>Equipment ${inr(c.base)} · Operator ${inr(c.op)} · Delivery ${inr(c.dl)}</p><h2>Total ${inr(c.tot)}</h2><div class="tabs">${['UPI','Card','Net Banking','Wallet','Cash'].map((m,i)=>`<button class="${i?'':'on'}" data-pm>${m}</button>`).join('')}</div><button class="btn" id="cp">Confirm Payment</button> <button class="btn ghost" data-x>Cancel</button>`);
$('#cp').onclick=()=>{$('#cp').textContent='Processing…';setTimeout(()=>{S.bookings.unshift({id:Date.now(),rid:+id,status:'Upcoming',date:bk.s+' Oct 2026',time:'8 AM – 4 PM',amt:c.tot});S.notes.unshift('Payment confirmed '+inr(c.tot));modal();bk={s:'',e:'',op:0,del:0};toast('Your booking request has been sent successfully.');tab='Upcoming';location.hash='#/bookings'},900)}}
document.addEventListener('click',e=>{const t=e.target,d=k=>t.closest(`[${k}]`);let x;
if(x=d('data-fav')){const i=+x.dataset.fav;S.fav.has(i)?S.fav.delete(i):S.fav.add(i);x.textContent=S.fav.has(i)?'❤️':'♡';toast(S.fav.has(i)?'Saved':'Removed from saved')}
else if(x=d('data-cat')){F.cat=x.dataset.cat;location.hash='#/find'}
else if(x=d('data-d')){if(x.classList.contains('bk'))return toast('That date is already booked.',1);const v=+x.dataset.d;(!bk.s||bk.e)?(bk.s=v,bk.e=''):(bk.e=v);render()}
else if(x=d('data-book')){const c=calc(RES.find(r=>r.id==x.dataset.book));if(!c.n)return toast('Select a start date first.',1);pay(x.dataset.book)}
else if(x=d('data-tab')){tab=x.dataset.tab;render()}
else if(x=d('data-cancel')){modal(`<h3>Cancel booking?</h3><p class="sub">This cannot be undone.</p><div class="row"><button class="btn red" id="cy">Yes, cancel</button><button class="btn ghost" data-x>Keep</button></div>`);$('#cy').onclick=()=>{S.bookings.find(b=>b.id==x.dataset.cancel).status='Cancelled';modal();toast('Booking cancelled.');render()}}
else if(x=d('data-review')){modal(`<h3>Rate your experience</h3><div style="font-size:30px" id="st">${[1,2,3,4,5].map(i=>`<span data-s="${i}" style="cursor:pointer">☆</span>`).join('')}</div>${['Equipment condition','Owner reliability','Communication','Timeliness','Payment experience'].map(c=>`<p class="meta">✔ ${c}</p>`).join('')}<textarea placeholder="Write a review"></textarea><div class="row" style="margin-top:10px"><button class="btn" id="rv">Submit review</button></div>`);$('#rv').onclick=()=>{modal();toast('Review submitted.')}}
else if(x=d('data-s')){$$('#st span').forEach((s,i)=>s.textContent=i<+x.dataset.s?'⭐':'☆')}
else if(x=d('data-step')){const n=+x.dataset.step;if(step==2&&n>0&&!$('#d_name').value.trim())return toast('Enter a resource name.',1);if(step==2)draft.name=$('#d_name').value;if(step==4)draft.price=$('#d_p').value;step+=n;render()}
else if(d('data-publish')){if(!draft.price)return toast('Set an hourly price first.',1);RES.unshift({id:RES.length+1,name:draft.name,cat:'Farming Tools',emoji:'🌱',price:+draft.price,unit:'hour',rating:5,dist:0.5,cond:'Excellent',op:0,del:0,year:2026,brand:'New',owner:'You',loc:'Chengalpattu',bg:COL[0],hours:0,booked:[],pending:[],pop:0});step=1;draft={};toast('Resource published.');location.hash='#/find'}
else if(x=d('data-join')){const c=S.comm[x.dataset.join];c.joined=!c.joined;c.members+=c.joined?1:-1;toast(c.joined?'Joined '+c.n:'Left community');render()}
else if(x=d('data-chat')){chat=+x.dataset.chat;render()}
else if(d('data-msg')){location.hash='#/messages'}
else if(d('data-report')){e.preventDefault();rep()}
else if(d('data-x'))modal();
else if(x=d('data-t'))toast(x.dataset.t)
else if(d('data-resched'))toast('Reschedule request sent to owner.')
else if(d('data-pm')){$$('[data-pm]').forEach(b=>b.classList.remove('on'));t.classList.add('on')}
else if(d('data-edit')){modal(`<h3>Edit profile</h3><label>Name</label><input id="en" value="${S.name||'Ravi Kumar'}"><div class="row" style="margin-top:12px"><button class="btn" id="es">Save changes</button></div>`);$('#es').onclick=()=>{S.name=$('#en').value||'Ravi Kumar';modal();toast('Profile saved.');render()}}
else if(t.id=='rs'){if(!$('#rd').value.trim())return toast('Add a description.',1);modal();toast('Report submitted. Our team will review it.')}
else if(t.closest('#bell')){modal(`<h3>Notifications</h3>${S.notes.map(n=>`<p class="panel" style="margin:6px 0">${n}</p>`).join('')}<button class="btn ghost" data-x>Close</button>`)}
else if(t.closest('#bg'))$('#nav').classList.toggle('open');
else if(t.id=='smb'){$('#smr').innerHTML='<p class="sub">Matching…</p>';setTimeout(()=>$('#smr').innerHTML=`<div class="panel" style="margin-top:10px"><b>Recommended: Kubota Combine Harvester</b><p>₹2,500/acre · ⭐ 4.9 · 📍 6 km · Available Oct 12</p><h3>Estimated cost: ₹12,500</h3><a class="btn y" href="#/res/4">Book Recommended Equipment</a></div>`,700)}});
document.addEventListener('input',e=>{const i=e.target;if(i.id=='fq'){F.q=i.value;runFind()}if(i.id=='fp'){F.max=+i.value;i.previousElementSibling.textContent='Max price: '+inr(F.max);runFind()}});
document.addEventListener('change',e=>{const i=e.target,m={fc:['cat',i.value],fo:['op',+i.checked],fd:['del',+i.checked],fs:['sort',i.value]};if(m[i.id]){F[m[i.id][0]]=m[i.id][1];runFind()}if(i.id=='bo'){bk.op=+i.checked;render()}if(i.id=='bd'){bk.del=+i.checked;render()}});
document.addEventListener('submit',e=>{e.preventDefault();if(e.target.id=='hs'){F.q=$('#hq').value;F.cat=$('#hc').value;location.hash='#/find'}
if(e.target.id=='cf'){const v=$('#ci').value.trim();if(!v)return;S.chats[chat].m.push(['me',v]);render();setTimeout(()=>{S.chats[chat].m.push(['them','Sure, I\'ll confirm shortly.']);if(location.hash=='#/messages')render()},1200)}});
addEventListener('hashchange',render);render();
