const SEV=['Mild','Moderate','Severe','Emergency'],SYM=['Fever','Cough','Loss of appetite','Diarrhea','Wounds','Swelling','Weakness'];
crud({store:'health',title:'Health Records',add:'Add Health Record',
 cols:[['animal','Animal'],['disease','Disease'],['symptoms','Symptoms'],['date','Detected'],['severity','Severity'],['temp','Temp °C'],['status','Treatment status']],
 fields:[['animal','Animal','select',names],['symptoms','Symptoms','text',0,1],['disease','Disease (if known)','text'],['date','Date detected','date',0,1],['severity','Severity','select',SEV],['temp','Temperature (°C)','number'],['status','Treatment status','select',['Monitoring','Under Treatment','Completed']],['notes','Notes','textarea']],
 filters:[['severity','Severities',SEV]],
 top:()=>`<div class="card" id="qc" style="margin-bottom:16px"><h3>⚡ Quick Health Check</h3><label>Animal<select id="qa">${names().map(n=>`<option>${n}</option>`).join('')}</select></label><div class="chk">${SYM.map(s=>`<label><input type="checkbox" value="${s}">${s}</label>`).join('')}</div><button class="btn" id="qb">Check now</button><div id="qr"></div></div>`,
 after:(el,upd)=>{const b=$('#qb');if(!b||b.dataset.on)return;b.dataset.on=1;
  b.onclick=()=>{const s=$$('#qc .chk input:checked').map(i=>i.value),n=$('#qa').value;if(!s.length)return toast('Select at least one symptom','err');
   const urgent=s.length>=3||(s.includes('Weakness')&&s.includes('Fever')),st=urgent?'Under Treatment':'Monitoring';
   $('#qr').innerHTML=`<div class="warn"><b>${esc(n)}: ${badge(st)}</b><p>⚠️ ${urgent?'Several warning signs together. Please contact a veterinarian today.':'Keep the animal comfortable, with clean water and shade, and watch closely. If signs continue or worsen, contact a veterinarian.'}</p><small>This is only a guide, not a diagnosis. Do not give medicines without veterinary advice.</small><p><button class="btn" id="qs">Save to records</button> <a class="btn ghost" href="appointments.html?add=1">Book vet</a></p></div>`;
   $('#qs').onclick=()=>{const h=DB.all('health');h.unshift({_id:uid(),animal:n,symptoms:s.join(', '),disease:'',date:new Date().toISOString().slice(0,10),severity:urgent?'Moderate':'Mild',temp:'',status:st,notes:'Quick health check'});DB.set('health',h);const A=DB.all('animals');A.find(a=>a.name==n).status=st;DB.set('animals',A);toast('Saved & status updated ✅');setTimeout(()=>location.reload(),700)}}}});
